server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /ingest/ {
        proxy_pass http://backend:8000/ingest/;
    }
    location /screen/ {
        proxy_pass http://backend:8000/screen/;
    }
    location /audit/ {
        proxy_pass http://backend:8000/audit/;
    }
    location /health {
        proxy_pass http://backend:8000/health;
    }
    location /aims/ {
        proxy_pass http://backend:8000/aims/;
    }
    location /hitl/ {
        proxy_pass http://backend:8000/hitl/;
    }
}
